apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: myheartbeat
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          # See https://github.com/envoyproxy/envoy-wasm/blob/master/generated_api_shadow/envoy/extensions/filters/http/wasm/v3/wasm.proto
          # See https://github.com/envoyproxy/envoy-wasm/blob/master/generated_api_shadow/envoy/extensions/wasm/v3/wasm.proto
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              # 'configuration' available at root_context.getConfiguration()
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: "http://example.com/"
              # root_id MUST match registerRootContext() 2nd param
              root_id: experiment-1.8
              vm_config:
                code:
                  # See https://github.com/envoyproxy/envoy-wasm/blob/master/api/envoy/config/core/v3/base.proto
                  local:
                    filename: /var/local/wasm/new-filter.wasm
                runtime: envoy.wasm.runtime.v8
                vm_id: myexperiment-1.8
  workloadSelector:
    labels:
      app: httpbin
